modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "lilwings"
version = "${version}"
displayName = "Lil' Wings"
authors = "Owner & Artist: Kekie6 //n Developer: CodexAdrian //n Developer: abused_master //n Artist: Frogipher"
description = '''
lil butterfly mod that does lil butterfly things
'''
#logoFile = ""

[[dependencies.lilwings]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lilwings]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lilwings]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.1.39,)"
ordering = "NONE"
side = "BOTH"